### ISSUE TITLE
invector/ai.lua:225: attempt to index upvalue 'cross' (a nil value)

### ISSUE THREAD

**Issue by Emojigit** [Dumpster-Studios/Invector#1]
AsyncErr: Lua: Runtime error from mod 'invector' in callback luaentity_Step(): ...rver/minetest/bin/../games/Invector/mods/invector/ai.lua:225: attempt to index upvalue 'cross' (a nil value)
stack traceback:
	...rver/minetest/bin/../games/Invector/mods/invector/ai.lua:225: in function 'eyesight'
	...rver/minetest/bin/../games/Invector/mods/invector/ai.lua:237: in function 'think'
	...etest/bin/../games/Invector/mods/invector/karts/kart.lua:448: in function <...etest/bin/../games/Invector/mods/invector/karts/kart.lua:272>

**Comment by Jordach** [comment]
This issue has been resolved by PR #2.
